### ISSUE TITLE
Entensions page jumps and is hard to navigate when selecting/deselecting plugins

### ISSUE THREAD

**Issue by rhys100** [decentespresso/de1app#289] opened 2024-01-04 22:41 UTC
latestly nightly, been an issue for quite a long time however.
samsung a8
1900x1200 resolution

https://photos.app.goo.gl/Wnbv32EEZrW79JRTA

**Comment by decentjohn** [comment] 2024-01-05 10:11
Sorry, I cannot understand what the problem is. I've watched the video. Can you explain?

**Comment by decentjohn** [comment] 2024-01-05 10:12
Is your issue that the [x] checkboxes are difficult to select?  That is a problem on all resolutions, and needs to be improved.

**Comment by ebengoechea** [comment] 2024-01-05 13:39
It's not that they're difficult to select, it's that, if you select a plugin that is not in the list of the 1st elements that are visible, when you tap to enable or disable the plugin, the listbox scrolls to the top, and the just selected item is no longer visible.

That's a bug that it's there since Johanna created it, if I remember correctly.

**Comment by decentjohn** [comment] 2024-01-05 14:23
Got it.  I think the check-box GUI for "unhide profiles" doesn't suffer from this bug, right @rhys100 ?

**Comment by rhys100** [comment] 2024-01-07 04:48
> If I understand it well, it's not that they're difficult to select, it's that, if you select a plugin that is not in the list of the 1st elements that are visible, when you tap to enable or disable the plugin, the listbox scrolls to the top, and the just selected/deselected item is no longer visible.
> 
> I've experienced it a lot of times too, and if I remember correctly, it's a bug that it's there since Johanna created it.

correct. its quite annoying as you have to scroll twice to get to the settings of the plugin you just turned on and the scroll bar is whack

**Comment by decentjohn** [comment] 2024-01-08 11:59
Gotcha, I've got that on my todo list.

Probably best, would be completely getting rid of a scrolling checkbox approach, and using something from DUI.  @ebengoechea

**Comment by decentjohn** [comment] 2024-09-08 10:24
fixed in previous de1app

**Closed by decentjohn** 2024-09-08 10:24 UTC
