### ISSUE TITLE
new resolutions not resizing skins correctly

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#182] opened 2021-07-02 04:34 UTC
@ebengoechea 

Seems that moving photoscale to dui has broken something:

The settings pages resize correctly, but the skin does not.

```
2021-07-02 12:31:49.080 DEBUG: ::dui::image resizing image /Users/john/d/admin/code/de1app/de1plus/skins/default/2560x1600/settings_1.png to /Users/john/d/admin/code/de1app/de1plus/skins/default/480x300/settings_1.png
2021-07-02 12:31:49.164 DEBUG: photoscale _resize_778 0.1875 0.1875
2021-07-02 12:31:49.939 WARNING: ::dui::image image file 'espresso_3.png' not found
2021-07-02 12:31:49.940 WARNING: ::dui::image image file 'espresso_3_zoomed.png' not found
```

```
[log.txt](https://github.com/decentespresso/de1app/files/6752074/log.txt)
```

**Comment by ebengoechea** [comment] 2021-07-02 15:09
@decentjohn You're not using the last nightly version, according to the log you're on v1.36.4-11. Probably the problem is still present (I'm testing), but it's hard to know given that that code has have some changes recently.

**Comment by ebengoechea** [comment] 2021-07-02 16:38
New commit on PR #181 fixes this bug.

**Comment by Mimoja** [comment] 2021-07-05 06:06
Merged.

**Comment by decentjohn** [comment] 2021-07-12 06:24
woohoo

![Screen Shot 2021-07-12 at 2 24 00 PM](https://user-images.githubusercontent.com/11965250/125240561-db229c00-e31c-11eb-8106-11a8965494c2.jpg)

**Closed** 2021-07-12 06:25 UTC
